-- ============================================================
--  Projeto T  ·  (histórico)
--
--  A partir da Fase 0, o schema é de responsabilidade do ALEMBIC.
--  Este arquivo NÃO cria mais tabelas — o container backend roda
--  `alembic upgrade head` no startup. Ver docs/architecture.md.
--
--  Mantido apenas como referência. O mount em docker-compose.yml
--  foi removido; pode ser reaproveitado futuramente para seeds.
-- ============================================================
